import fs from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
const dir=fileURLToPath(new URL('../dist/',import.meta.url));const {hairPresets,outfitPresets}=await import(dir+'presets.js');const {parameterDefaults,parameterRanges}=await import(dir+'parameters.js');const text=await fs.readFile(dir+'app.js','utf8');const prefix=text.slice(text.indexOf('const defaults ='),text.indexOf('let state='));const choice=text.slice(text.indexOf('function choicesFor('),text.indexOf('let toastTimer;'));const normalize=text.slice(text.indexOf('function normalize('),text.indexOf('function element('));const normalizeState=new Function('hairPresets','outfitPresets','parameterDefaults','parameterRanges',prefix+'let state={...defaults};'+choice+normalize+'return normalize;')(hairPresets,outfitPresets,parameterDefaults,parameterRanges);
for(const gender of ['female','male'])for(const [hair] of hairPresets[gender])for(const [clothes] of outfitPresets[gender]){const expected={name:'预设存档',gender,hair,clothes,height:72};const actual=normalizeState(JSON.parse(JSON.stringify(expected)));if(actual.hair!==hair||actual.clothes!==clothes||actual.name!==expected.name||actual.height!==72)throw Error('preset roundtrip failed');}
const old=normalizeState({name:'旧角色',gender:'male',hair:'long',clothes:'formal',height:70});if(old.hair!=='source'||old.clothes!=='source'||old.height!==70)throw Error('legacy migration failed');
const invalid=normalizeState({gender:'male',hair:'wavePreset',clothes:'classicPreset'});if(invalid.hair!=='source'||invalid.clothes!=='source')throw Error('gender guard failed');
console.log('PASS all 36 preset archive roundtrips, legacy archive and gender switch guards');

for(const key of Object.keys(parameterDefaults)){if(normalizeState({})[key]!==50)throw Error('old default');if(normalizeState({[key]:123})[key]!==100)throw Error('clamp');if(normalizeState({[key]:NaN})[key]!==50)throw Error('finite guard');if(normalizeState({[key]:73})[key]!==73)throw Error('new roundtrip');}console.log('PASS new parameter defaults, bounds and archive values');
